### ISSUE TITLE
以太坊账户模型与比特币UTXO对比

### ISSUE THREAD

**Issue by gitferry** [mochain/taste-of-ethereum#13]

**Comment by MarkSir** [comment]
## 余额的显示原理
在比特币系统中没有账户的概念，所以也就没有账户余额的概念，但是却有UTXO的概念。

以太坊系统中是有外部账户和合约账户的概念的，每个地址对应一个以太坊的账户，而余额就是账户状态的一部分。

## 比特币的UTXO模型
UTXO(Unspent Transaction Output)未花费交易输出。

UTXO是不可拆分的，也就是说使用过之后一定有新的UTXO产生，可以把UTXO类比成纸币。

### 举例：

#### 1:

你有一张20元的纸币，想买一个价值10元的苹果，商家会收到10元，你会收到找零的10元。也就是说你将20元拆成了两个10元，一份为找零之后的10元，一份为支付给商家的10元。

#### 2:

你又用找零之后的10元买了一个价值5元的沙拉酱，支付给商家5元，你收到找零5元。

#### 总结：

例子1就是一笔交易，20元为交易的输入，找零的10元与支付给商家的10元是交易的输出。也就是这两个10元就是UTXO。

例子2也是一笔交易，找零的10元作为交易的输入，找零的5元与支付给商家的5元是交易的输出。

一笔交易的输入一定是之前某笔交易的输出。

## 以太坊账户模型
以太坊中两种类型的账户：
* 外部账户(Externally Owned Accounts 或EOA)：被私钥控制，没有与合约代码相关联，有余额。
* 合约账户：被合约代码控制，同样有余额。只能被外部账户调用来激活。

当合约账户被调用时，存储其中的智能合约会在矿工处的虚拟机中自动执行，并消耗一定的燃料。燃料通过外部账户中的以太币进行购买。

每个账户都有一个与之关联的状态(state)和一个20字节的地址(address)。在以太坊中一个地址是160位的标识符，用来识别账户的。
（私钥生成公钥，公钥的最后20个字节就是账户的地址。这里需要注意一下，以太坊网络没有对地址是否有效进行判断，所以在转账的时候，一定要注意地址是否正确）

每个账户都维护自己的“状态”，所有账户的状态代表的都是以太坊网络的“状态”。
### 以太坊账户的状态
以太坊的账户状态由四个部分组成
* nonce：外部账户代表交易次数。合约账户，nonce代表创建的合约序号。
* balance： 此地址拥有Wei的数量。1Ether=10^18Wei（Wei是以太坊代币的一个单位）
* storageRoot： Merkle Patricia树的根节点Hash值，Merkle树会将此账户存储内容的Hash值进行编码，默认是空值。
* codeHash：账户EVM（以太坊虚拟机）代码的hash值。合约账户就是代码的Hash值。外部账户就是空字符串的Hash值


## 比特币的UTXO模型与以太坊的账户模型优缺点分析
### UTXO优点
* 私密性强：每一笔交易的找零可以重新指定一个新的地址。
* 并行交易：一个交易发送者发送两笔独立的交易时，他们可以小心地花费独立的 UTXO ，因此这些交易也可以用任意次序来处理。
* 不可分割性：UTXO是不能分割的，交易之后原有的UTXO就会消失，并产生新的UTXO。
* 可追溯性：支持历史追溯。


### 账户模型优点
* 快速获取余额：比特币需要将指定地址所拥有的所有UTXO中的未花费交易总值整合。
* 存储空间小：输入输出只有一个。
* 相对于UTXO模型比较容易实现智能合约。
* 易用性高：易于理解和编程。
* 容易查询状态的变更。

## 总结
单纯的比较两种模型的优缺点有点片面，还是需要根据项目要求来选择合适的模型，毕竟两者的定位不同。

（如果有理解错了的地方，希望大家指正，共同学习）
